
project_id = "ttidnpncifqtetnhcdhq"
spec_version = "v0"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

[functions]
[functions.realtime-airtable-sync]
verify_jwt = true
[functions.listener-service]
verify_jwt = true
[functions.facebook-capi]
verify_jwt = false

[observability]
otel_endpoint = ""
otel_http_port = 54329
otel_grpc_port = 54330

[experimental]
